### ISSUE TITLE
DayPlanner not showing in calendar view

### ISSUE THREAD

**Issue by javiercuadrado** [ivan-lednev/obsidian-day-planner#268]
Time slots are not showing any more after Obsidian update. The rest of the features are still working.

Obsidian version: 1.4.14 Desktop on Mac Ventura 13.5.2

Exception on dev console:
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'isSame')
    at DayPlanner.handleActiveLeafChanged (plugin:obsidian-day-planner:22345:29)
    at e.tryTrigger (app.js:1:695457)
    at e.trigger (app.js:1:695390)
    at t.trigger (app.js:1:2026234)
    at t.activeLeafEvents (app.js:1:2012130)
    at l (app.js:1:254362)
    at c (app.js:1:254478)

**Comment by ivan-lednev** [comment]
Hello, @javiercuadrado, please update and re-check. Make sure the Dataview plugin is installed.

**Comment by ivan-lednev** [comment]
Closing this as stale.
