### ISSUE TITLE
Request: Setting to toggle off drag-and-drop unscheduled tasks

### ISSUE THREAD

**Issue by epi-sam** [ivan-lednev/obsidian-day-planner#296]
Thank you for revitalizing the Day Planner plugin, it's getting really cool!

Background: New 0.13.0 feature allows drag-and-drop unscheduled tasks directly into the timeline.

Issue: No option to remove this (visual distraction, includes already-completed tasks), only 2 tasks visible at any time, hard to sort through.

Proposal: setting toggle to remove this field and/or pane slider to expand/contract the size of the field.

**Comment by ivan-lednev** [comment]
Please update and re-check

**Comment by epi-sam** [comment]
Hey, thanks for the update - unfortunately it basically erased all my workspaces, closed all files, and left the timeline empty (see image)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/96550052/df120f23-289c-470f-8806-59c61359162e)

edit: I found the toggle in the timeline settings menu - I'm unable to change any of the settings, or get the menu to close after opening it.

**Comment by ivan-lednev** [comment]
Did you see any errors in the developer console? (`ctrl + shift + I`)? I updated the plugin in my own vault, then reinstalled it just to make sure, and didn't see any of this.

**Comment by epi-sam** [comment]
```
app.js:1 Obsidian Developer Console
plugin:shortcuts-extender:83 e
plugin:nldates-obsidian:9043 Loading natural language date parser plugin
plugin:mousewheel-image-zoom:283 Loaded: Mousewheel image zoom
plugin:table-editor-obsidian:28663 loading markdown-table-editor plugin
plugin:oz-clear-unused-images:1 Clear Unused Images plugin loaded...
plugin:obsidian-markdown-formatting-assistant-plugin:2364 Object
plugin:obsidian-markdown-formatting-assistant-plugin:4815 loading obsidian-markdown-formatting-assistant-plugin
plugin:file-explorer-note-count:933 loading FileExplorerNoteCount
plugin:obsidian-link-converter:1 Link Converter Loading...
plugin:wikilinks-to-mdlinks-obsidian:41 loading wikilinks-to-mdlinks plugin...
plugin:dataview:19919 Dataview: version 0.5.61 (requires obsidian 0.13.11)
plugin:oz-image-plugin:188 Image in Editor Plugin is loaded
plugin:obsidian-statusbar-pomo:945 Loading status bar pomodoro timer
plugin:dataview:12740 Dataview: all 1062 files have been indexed in 2.378s (1062 cached, 0 skipped).
11plugin:file-explorer-note-count:889 file-explorer not found, retrying...
plugin:file-explorer-note-count:887 failed to get file-explorer
tryGetView @ plugin:file-explorer-note-count:887
app.js:1 Failed to open view TypeError: Cannot read properties of undefined (reading 'after')
    at decorate (plugin:obsidian-day-planner:27506:20)
    at refresh (plugin:obsidian-day-planner:27540:5)
    at renderTaskMarkdown (plugin:obsidian-day-planner:27542:3)
    at Object.m (plugin:obsidian-day-planner:27570:83)
    at mount_component (plugin:obsidian-day-planner:22368:24)
    at Object.m (plugin:obsidian-day-planner:27690:7)
    at mount_component (plugin:obsidian-day-planner:22368:24)
    at Object.m (plugin:obsidian-day-planner:30941:7)
    at Object.m (plugin:obsidian-day-planner:31004:26)
    at Object.m (plugin:obsidian-day-planner:30644:22)
    at mount_component (plugin:obsidian-day-planner:22368:24)
    at Object.m (plugin:obsidian-day-planner:30825:7)
    at Object.m (plugin:obsidian-day-planner:30752:18)
    at Object.m (plugin:obsidian-day-planner:31711:18)
    at mount_component (plugin:obsidian-day-planner:22368:24)
    at init (plugin:obsidian-day-planner:22451:5)
    at new Task_container (plugin:obsidian-day-planner:31974:5)
    at TimelineView.onOpen (plugin:obsidian-day-planner:31997:21)
    at TimelineView.<anonymous> (app.js:1:1287590)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.open (app.js:1:1287447)
    at t.<anonymous> (app.js:1:1891059)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
(anonymous) @ app.js:1
plugin:obsidian-day-planner:27611 Uncaught (in promise) TypeError: dispose is not a function
    at Object.d (plugin:obsidian-day-planner:27611:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:27780:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30976:7)
    at destroy_each (plugin:obsidian-day-planner:21954:21)
    at Object.d (plugin:obsidian-day-planner:31051:7)
    at Object.d (plugin:obsidian-day-planner:30692:22)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30848:7)
    at eval (plugin:obsidian-day-planner:22214:17)
    at run (plugin:obsidian-day-planner:21699:10)
    at Array.forEach (<anonymous>)
    at run_all (plugin:obsidian-day-planner:21705:7)
    at check_outros (plugin:obsidian-day-planner:22195:5)
    at Object.p (plugin:obsidian-day-planner:30785:9)
    at Object.p (plugin:obsidian-day-planner:31753:20)
    at update (plugin:obsidian-day-planner:22172:32)
    at flush (plugin:obsidian-day-planner:22138:9)
app.js:1 Failed to open view TypeError: dispose is not a function
    at Object.d (plugin:obsidian-day-planner:27611:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:27780:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30976:7)
    at destroy_each (plugin:obsidian-day-planner:21954:21)
    at Object.d (plugin:obsidian-day-planner:31051:7)
    at Object.d (plugin:obsidian-day-planner:30692:22)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30848:7)
    at eval (plugin:obsidian-day-planner:22214:17)
    at run (plugin:obsidian-day-planner:21699:10)
    at Array.forEach (<anonymous>)
    at run_all (plugin:obsidian-day-planner:21705:7)
    at check_outros (plugin:obsidian-day-planner:22195:5)
    at Object.p (plugin:obsidian-day-planner:30785:9)
    at Object.p (plugin:obsidian-day-planner:31753:20)
    at update (plugin:obsidian-day-planner:22172:32)
    at flush (plugin:obsidian-day-planner:22138:9)
    at init (plugin:obsidian-day-planner:22453:5)
    at new Header_actions (plugin:obsidian-day-planner:32293:5)
    at WeeklyView.onOpen (plugin:obsidian-day-planner:32694:35)
    at WeeklyView.<anonymous> (app.js:1:1287590)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.open (app.js:1:1287447)
    at t.<anonymous> (app.js:1:1891059)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
(anonymous) @ app.js:1
plugin:obsidian-day-planner:27611 Uncaught (in promise) TypeError: dispose is not a function
    at Object.d (plugin:obsidian-day-planner:27611:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:27780:7)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30976:7)
    at destroy_each (plugin:obsidian-day-planner:21954:21)
    at Object.d (plugin:obsidian-day-planner:31051:7)
    at Object.d (plugin:obsidian-day-planner:30692:22)
    at destroy_component (plugin:obsidian-day-planner:22387:32)
    at Object.d (plugin:obsidian-day-planner:30848:7)
    at eval (plugin:obsidian-day-planner:22214:17)
    at run (plugin:obsidian-day-planner:21699:10)
    at Array.forEach (<anonymous>)
    at run_all (plugin:obsidian-day-planner:21705:7)
    at check_outros (plugin:obsidian-day-planner:22195:5)
    at Object.p (plugin:obsidian-day-planner:30785:9)
    at Object.p (plugin:obsidian-day-planner:31753:20)
    at update (plugin:obsidian-day-planner:22172:32)
    at flush (plugin:obsidian-day-planner:22138:9)
app.js:1 Measure loop restarted more than 5 times
e.measure @ app.js:1
e.onScrollChanged @ app.js:1
e.onScroll @ app.js:1
```

**Comment by ivan-lednev** [comment]
Okay, this is helpful. I deleted this release for now, since this is a major issue.

**Comment by epi-sam** [comment]
Thanks - some of my workspaces are functional again as expected, after disabling the plugin, and some are not.  It's very odd behavior, not something I've seen before.

**Comment by ivan-lednev** [comment]
I think this is because the error happened during view initialization. Installing the old version and reloading Obsidian should fix it.

**Comment by epi-sam** [comment]
OK.  If helpful for debugging, I'm using the Workspace Plus plugin, in case there's an interaction.

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by epi-sam** [comment]
Sorry it took me a minute to check - I tried again, and it's working well.  Thank you!
